# opensubtitles

###
# @name formats
GET {{url}}/api/v1/infos/formats
Api-Key: {{key}}

###
# @name subtitles
GET {{url}}/api/v1/subtitles?
    query=mr robot&
    languages=pl
Api-Key: {{key}}

###
# @name download
POST {{url}}/api/v1/download
Api-Key: {{key}}
Content-Type: application/json

{
  "file_id": 9889615
}

###
# @name features
GET {{url}}/api/v1/subtitles?
    query=mr robot s01e01&
    languages=pl
Api-Key: {{key}}
