pub mod app;
mod downloader;
mod input_handler;
mod language_widget;
mod search_widget;
mod spinner;
mod subs_widget;
mod subtitles_fetcher;
mod actions;
mod status_widget;
mod login_widget;
mod account_widget;
mod user_widget;
mod account_screen;
mod languages_screen;
