pub mod app;
mod downloader;
mod input_handler;
mod query_widget;
mod spinner;
mod subs_list_widget;
mod subtitles_fetcher;
mod actions;
mod status_widget;
mod login_widget;
mod account_widget;
mod user_widget;
mod account_screen;
mod languages_screen;
mod search_screen;
mod nav_widget;
