pub mod app;
mod downloader;
mod input_handler;
mod language_widget;
mod search_widget;
mod spinner;
mod subs_widget;
mod subtitles_fetcher;
mod ui_messages;
mod status_widget;
mod login_widget;
mod logged_in_widget;
mod user_widget;
